# model
model_name: "DynLatte-XL/2"
vae_checkpoint: "models/sd-vae-ft-mse.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: False
dtype: "fp16"
embed_dim: 72
embed_method: "rotate"
patch_size: 2
image_size: 384
max_frames: 32

# sampling
sampling_steps: 50
guidance_scale: 1.0
seed: 42
ddim_sampling: True
