import transformers
from packaging import version

from . import (
    albert,
    aria,
    auto,
    bart,
    bert,
    big_bird,
    bigbird_pegasus,
    bit,
    blip,
    blip_2,
    camembert,
    canine,
    chameleon,
    clap,
    clip,
    convbert,
    convnext,
    convnextv2,
    depth_anything,
    dinov2,
    dpt,
    fuyu,
    gemma,
    gemma2,
    gemma3,
    glm,
    glpn,
    gpt2,
    granite,
    granitemoe,
    granitemoeshared,
    hiera,
    hubert,
    idefics,
    idefics2,
    idefics3,
    ijepa,
    imagegpt,
    levit,
    llama,
    llava,
    llava_next,
    llava_next_video,
    llava_onevision,
    m2m_100,
    megatron_bert,
    minicpm4,
    mistral,
    mixtral,
    mobilebert,
    mpt,
    mvp,
    opt,
    owlvit,
    paligemma,
    persimmon,
    phi,
    phi3,
    qwen2,
    qwen2_5_omni,
    qwen2_5_vl,
    qwen2_audio,
    qwen2_vl,
    siglip2,
    roberta,
    segformer,
    siglip,
    smolvlm,
    speecht5,
    starcoder2,
    swin2sr,
    switch_transformers,
    t5,
    umt5,
    vilt,
    vision_encoder_decoder,
    vit,
    vits,
    wav2vec2,
    xlm_roberta,
    yolos,
)

if version.parse(transformers.__version__) >= version.parse("4.51.0"):
    from . import qwen3

if version.parse(transformers.__version__) >= version.parse("4.51.3"):
    from . import glm4

if version.parse(transformers.__version__) >= version.parse("4.53.0"):
    from . import glm4v, minimax, vjepa2
