nsfw:
  concepts:
    sexual: 0.18
    nude: 0.19
    sex: 0.21
    18+: 0.21
    naked: 0.19
    nsfw: 0.19
    porn: 0.19
    dick: 0.19
    vagina: 0.19
    naked child: 0.22
    explicit content: 0.19
    uncensored: 0.19
    fuck: 0.19
    nipples: 0.21
    visible nipples: 0.21
    naked breasts: 0.21
    areola: 0.2
  action: obfuscate
special:
  concepts:
    young girl: 0.20
    young child: 0.22
    little girl: 0.19
