nsfw:
  concepts:
    sexual: 0.2
    nude: 0.20
    sex: 0.206
    18+: 0.21
    naked: 0.195
    nsfw: 0.2
    porn: 0.2
    dick: 0.19
    vagina: 0.19
    naked child: 0.22
    explicit content: 0.19
    uncensored: 0.2
    fuck: 0.2
    nipples: 0.2
    visible nipples: 0.21
    naked breasts: 0.214
    areola: 0.2
  action: obfuscate
special:
  concepts:
    little girl: 0.21
    little boy: 0.21
    young child: 0.21
    young girl: 0.22
    toddler: 0.21
    baby: 0.22
