environment:
  mode: 0
  debug: False
  seed: 42
  distributed: False
  enable_modelarts: False

train:
  epochs: 3
  temporal_only: True
  pretrained: /home/rustam/projects/mindone/models/videoldm/ms/svd_d19a808f.ckpt
  output_dir: output/
  sink_size: -1

  dataset:
    class_path: data.video_dataset.VideoDataset
    init_args:
      data_dir: /data1/webvid-10m/dataset/2M_val/
      metadata: videos.csv
      frames: 2
      step: 1

  dataloader:
    batch_size: 1
    shuffle: True
    drop_remainder: True

  scheduler:
    name: cosine_decay
    lr: 3.0e-5
    end_lr: 1.0e-7
    warmup_steps: 120

  optimizer:
    name: adamw
    betas: [ 0.9, 0.98 ]
    weight_decay: 0.01

  settings:
    drop_overflow_update: False
    gradient_accumulation_steps: 3
    clip_grad: False
    clip_norm: 1.0

LossScale:
  loss_scale_value: 1
  scale_factor: 2
  scale_window: 1000
