environment:
  mode: 0
  debug: False
  seed: 42
  distributed: False
  enable_modelarts: False

train:
  epochs: 5
  temporal_only: True
  pretrained: models/sd_v2-1_base-7c8d09ce.ckpt
  output_dir: output/videoldm_sd_v2.1/
  sink_size: 60

  dataset:
    class_path: data.video_dataset.VideoDataset
    init_args:
      data_dir: /data1/webvid-10m/dataset/2M_val/part0/00000
      metadata_dir: /home/rustam/projects/mindone/data/
      frames: 8
      step: 10

  dataloader:
    batch_size: 1
    shuffle: True
    drop_remainder: True

  scheduler:
    scheduler: cosine_decay
    lr: 1.0e-4
    min_lr: 1.0e-7
    warmup_steps: 120

  optimizer:
    name: adamw
    betas: [ 0.9, 0.98 ]
    weight_decay: 0.01

  settings:
    drop_overflow_update: True
    gradient_accumulation_steps: 3
    clip_grad: False
    clip_norm: 1.0

LossScale:
  loss_scale_value: 65536
  scale_factor: 2
  scale_window: 1000
