ckpt_path: "models/opensora_v1.1_stage3.ckpt"
t5_model_dir: "models/t5-v1_1-xxl/"
vae_checkpoint: "models/sd-vae-ft-ema.ckpt"

image_size: [240, 426]
num_frames: 16
frame_interval: 3
fps: 24
enable_flash_attention: True
enable_sequence_parallelism: True
model_max_length: 200
dtype: "fp32"
batch_size: 1

# sampling
sampling_steps: 100
guidance_scale: 7.0
guidance_channels: 3
seed: 42
ddim_sampling: False

# parallel
data_parallel: 1
model_parallel: 1
sequence_parallel: 2
add_datetime: False

captions:
- "Disco light leaks disco ball light reflections shaped rectangular and line with motion blur effect."
- "Cloudy moscow kremlin time lapse."
