ckpt_path: "models/opensora_v1.1_stage3.ckpt"
t5_model_dir: "models/t5-v1_1-xxl/"
vae_checkpoint: "models/sd-vae-ft-ema.ckpt"

image_size: [240, 426]
num_frames: 16
frame_interval: 3
fps: 24
enable_flash_attention: False
model_max_length: 200
dtype: "fp32"
batch_size: 1

# sampling
sampling_steps: 100
guidance_scale: 7.0
guidance_channels: 3
seed: 42
ddim_sampling: False

loop: 2
condition_frame_length: 4

captions:
  - "In an ornate, historical hall, a massive tidal wave peaks and begins to crash. Two surfers, seizing the moment, skillfully navigate the face of the wave."

mask_strategy:

reference_path:
