transformer:
    "activation_fn": "gelu-approximate"
    "attention_bias": True
    "attention_head_dim": 128
    "dropout": 0.0
    "flip_sin_to_cos": True
    "freq_shift": 0
    "in_channels": 16
    "max_text_seq_length": 226
    "norm_elementwise_affine": True
    "norm_eps": 1e-05
    "num_attention_heads": 48
    "num_layers": 64
    "out_channels": 16
    "patch_bias": False
    "patch_size": 2
    "patch_size_t": 2
    "sample_frames": 81
    "sample_height": 96
    "sample_width": 170
    "spatial_interpolation_scale": 1.875
    "temporal_compression_ratio": 4
    "temporal_interpolation_scale": 1.0
    "text_embed_dim": 4096
    "time_embed_dim": 512
    "timestep_activation_fn": "silu"
    "use_learned_positional_embeddings": False
    "use_rotary_positional_embeddings": True
