# task
condition: null
output_path: outputs/uncond

# model setting
image_size: 384
patch_size: 2
num_frames: 32
embed_dim: 72
embed_method: "rotate"
model_name: "DynLatte-XL/2"
dyn_latte_checkpoint: ""
vae_checkpoint: "models/sd-vae-ft-mse.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: False
dtype: "fp16"

# data setting
data_path: video/
dataset_sink_mode: False
num_parallel_workers: 4

# training hyper-params
start_learning_rate: 1e-4
scheduler: "constant"
warmup_steps: 100
train_batch_size: 1
gradient_accumulation_steps: 1
weight_decay: 0.01
epochs: 3000

use_ema: True
clip_grad: True
max_grad_norm: 1.0
ckpt_max_keep: 3
init_loss_scale: 65536

betas: [0.9, 0.999]
optim_eps: 1.e-6

# training process
log_interval: 1
ckpt_save_interval: 10
step_mode: False
