python opensora/train/train_causalvae.py \
    --batch_size 1 \
    --precision fp16 \
    --epochs 3000 \
    --ckpt_save_interval 500 \
    --output_dir results/causalvae \
    --video_path /remote-home1/dataset/data_split_tt \
    --video_num_frames 17 \
    --resolution 256 \
    --sample_rate 1 \
    --num_parallel_workers 8 \
    --load_from_checkpoint ./results/pretrained_488/
