t5_model_dir: "models/t5-v1_1-xxl/"

image_size: 256
num_frames: 16
fps: 8

checkpoint: "models/OpenSora-v1-HQ-16x256x256.ckpt"
vae_checkpoint: "models/sd-vae-ft-mse.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: False
dtype: "fp32"

# sampling
sampling_steps: 100
guidance_scale: 7.0
seed: 42
ddim_sampling: False

captions:
- "Disco light leaks disco ball light reflections shaped rectangular and line with motion blur effect."
- "Cloudy moscow kremlin time lapse"
- "Sharp knife to cut delicious smoked fish"
- "The girl received flowers as a gift. a gift for my birthday. the guy gave a girl flowers"
- "A baker turns freshly baked loaves of sourdough bread"
