condition: "text"
text_encoder: "t5"
clip_checkpoint: ""
t5_model_dir: "models/t5-v1_1-xxl/"

image_size: 512
num_frames: 16
model_name: "STDiT"
checkpoint: "models/OpenSora-v1-HQ-16x512x512.ckpt"
vae_checkpoint: "models/sd-vae-ft-mse.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: False
dtype: "fp32"

# sampling
sampling_steps: 100
guidance_scale: 7.0
seed: 42
ddim_sampling: False

captions:
- "A snowy forest landscape with a dirt road running through it. The road is flanked by trees covered in snow, and the ground is also covered in snow. The sun is shining, creating a bright and serene atmosphere. The road appears to be empty, and there are no people or animals visible in the video. The style of the video is a natural landscape shot, with a focus on the beauty of the snowy forest and the peacefulness of the road."
