# model
model_version: v1.2
pretrained_model_path: PATH_TO_YOUR_MODEL
model_max_length: 300
freeze_y_embedder: True

noise_scheduler: rflow
sample_method: logit-normal
use_timestep_transform: True

vae_type: OpenSoraVAE_V1_2
vae_checkpoint: models/OpenSora-VAE-v1.2/model.ckpt
vae_dtype: bf16
vae_micro_batch_size: 4
vae_micro_frame_size: 17  # keep it unchanged for the best results

enable_flash_attention: True
use_recompute: True

# data
num_parallel_workers: 2
num_workers_dataset: 2
prefetch_size: 1
max_rowsize: 256

# precision
amp_level: "O2"
dtype: bf16
loss_scaler_type: static
init_loss_scale: 1

# training hyper-params
scheduler: "constant"
start_learning_rate: 1.e-4
end_learning_rate: 1.e-4
warmup_steps: 500

clip_grad: True
max_grad_norm: 1.0
use_ema: True

optim: "adamw_re"
optim_eps: 1e-15
weight_decay: 0.

epochs: 1000
ckpt_save_interval: &save_interval 100

mask_ratios:
  random: 0.01
  interpolate: 0.002
  quarter_random: 0.002
  quarter_head: 0.002
  quarter_tail: 0.002
  quarter_head_tail: 0.002
  image_random: 0.0
  image_head: 0.22
  image_tail: 0.005
  image_head_tail: 0.005

bucket_config:
  # Structure: "resolution": { num_frames: [ keep_prob, batch_size ] }
  # Setting [ keep_prob, batch_size ] to [ 0.0, 0 ] forces longer videos into smaller resolution buckets
  "144p": { 1: [ 1.0, 475 ], 51: [ 1.0, 45 ], 102: [ 1.0, 22 ], 204: [ 1.0, 11 ], 408: [ 1.0, 5 ] }
  "256": { 1: [ 1.0, 297 ], 51: [ 0.5, 20 ], 102: [ 0.5, 10 ], 204: [ 0.5, 5 ], 408: [ [ 0.5, 0.5 ], 2 ] }
  "240p": { 1: [ 1.0, 297 ], 51: [ 0.5, 15 ], 102: [ 0.5, 7 ], 204: [ 0.5, 3 ], 408: [ [ 0.5, 0.4 ], 1 ] }
  "360p": { 1: [ 1.0, 141 ], 51: [ 0.5, 6 ], 102: [ 0.5, 3 ], 204: [ 0.5, 1 ], 323: [ [ 0.5, 0.3 ], 1 ], 408: [ 0.0, 0 ] }
  "512": { 1: [ 1.0, 141 ], 51: [ 0.5, 6 ], 102: [ 0.5, 3 ], 204: [ 0.5, 1 ], 289: [ [ 0.5, 0.2 ], 1 ], 408: [ 0.0, 0 ] }
  "480p": { 1: [ 1.0, 89 ], 51: [ 0.5, 3 ], 85: [ 0.5, 2 ], 170: [ [ 0.5, 0.5 ], 1 ], 408: [ 0.0, 0 ] }
  "720p": { 1: [ 0.3, 36 ], 51: [ 0.2, 1 ], 85: [ 0.1, 1 ], 204: [ 0.0, 0 ] }
  "1024": { 1: [ 0.3, 36 ], 51: [ 0.1, 1 ], 68: [ 0.1, 1 ], 204: [ 0.0, 0 ] }
  "1080p": { 1: [ 0.1, 5 ] }
  "2048": { 1: [ 0.05, 5 ] }


# ---------- Validation ----------
validate: True
val_interval: *save_interval
num_eval_timesteps: 10

val_csv_path:
val_video_folder:
val_text_embed_folder:
val_vae_latent_folder:

val_bucket_config:
  "144p": { 51: [ 1.0, 30 ], 102: [ 1.0, 20 ], 204: [ 1.0, 8 ], 408: [ 1.0, 4 ] }
  "240p": { 51: [ 1.0, 16 ], 102: [ 1.0, 8 ], 204: [ 1.0, 4 ], 408: [ 1.0, 2 ] }
  "360p": { 51: [ 1.0, 6 ], 102: [ 1.0, 3 ], 204: [ 1.0, 1 ], 340: [ 1.0, 1 ] }
  "480p": { 51: [ 1.0, 4 ], 102: [ 1.0, 2 ], 204: [ 1.0, 1 ] }
  "720p": { 51: [ 1.0, 1 ], 85: [ 1.0, 1 ] }
