# model
model_version: v1.2
pretrained_model_path: models/PixArt-Sigma-XL-2-2K-MS.ckpt
model_max_length: 300
freeze_y_embedder: True

noise_scheduler: rflow
sample_method: logit-normal
use_timestep_transform: True

vae_type: OpenSoraVAE_V1_2
vae_checkpoint: models/OpenSora-VAE-v1.2/model.ckpt
vae_dtype: bf16
vae_micro_batch_size: 4
vae_micro_frame_size: 17  # keep it unchanged for the best results

enable_flash_attention: True
use_recompute: True

# data
num_parallel_workers: 2
num_workers_dataset: 2
prefetch_size: 1
max_rowsize: 256

# precision
amp_level: "O2"
dtype: bf16
loss_scaler_type: static
init_loss_scale: 1

# training hyper-params
scheduler: "constant"
start_learning_rate: 1.e-4
end_learning_rate: 1.e-4
warmup_steps: 500

clip_grad: True
max_grad_norm: 1.0
use_ema: True

optim: "adamw_re"
optim_eps: 1e-15
weight_decay: 0.

epochs: 1000
ckpt_save_interval: &save_interval 100

mask_ratios:
  random: 0.05
  interpolate: 0.005
  quarter_random: 0.005
  quarter_head: 0.005
  quarter_tail: 0.005
  quarter_head_tail: 0.005
  image_random: 0.025
  image_head: 0.05
  image_tail: 0.025
  image_head_tail: 0.025

bucket_config:
  # Structure: "resolution": { num_frames: [ keep_prob, batch_size ] }
  # Setting [ keep_prob, batch_size ] to [ 0.0, 0 ] forces longer videos into smaller resolution buckets
  "144p": { 1: [ 1.0, 475 ], 51: [ 1.0, 45 ], 102: [ [ 1.0, 0.33 ], 22 ], 204: [ [ 1.0, 0.1 ], 11 ], 408: [ [ 1.0, 0.1 ], 5 ] }
  "256": { 1: [ 0.4, 297 ], 51: [ 0.5, 20 ], 102: [ [ 0.5, 0.33 ], 10 ], 204: [ [ 0.5, 0.1 ], 5 ], 408: [ [ 0.5, 0.1 ], 2 ] }
  "240p": { 1: [ 0.3, 297 ], 51: [ 0.4, 15 ], 102: [ [ 0.4, 0.33 ], 7 ], 204: [ [ 0.4, 0.1 ], 3 ], 408: [ [ 0.4, 0.1 ], 1 ] }
  "360p": { 1: [ 0.2, 141 ], 51: [ 0.15, 6 ], 102: [ [ 0.15, 0.33 ], 3 ], 204: [ [ 0.15, 0.1 ], 1 ], 323: [ [ 0.15, 0.1 ], 1 ] }
  "512": { 1: [ 0.1, 141 ] }
  "480p": { 1: [ 0.1, 89 ] }
  "720p": { 1: [ 0.05, 36 ] }
  "1024": { 1: [ 0.05, 36 ] }
  "1080p": { 1: [ 0.1, 5 ] }
  "2048": { 1: [ 0.1, 5 ] }


# ---------- Validation ----------
validate: False
