text_config:
  vocab_size: 49408
  hidden_size: 768
  intermediate_size: 2048
  num_hidden_layers: 12
  num_attention_heads: 12
  max_position_embeddings: 77
  hidden_act: "gelu"
  initializer_range: 0.02
  initializer_factor: 1.0

vision_config:
  hidden_size: 1024
  intermediate_size: 3072
  num_hidden_layers: 24
  num_attention_heads: 16
  image_size: 224
  patch_size: 14
  hidden_act: "gelu"
  initializer_range: 0.02
  initializer_factor: 1.0

dtype: float16  # type of tensors
projection_dim: 768  # feature dims
logit_scale_init_value: 2.6592
