# model
model_version: v1.1
pretrained_model_path: "models/opensora_v1.1_stage3.ckpt"
model_max_length: 200

enable_flash_attention: True
use_recompute: True
jit_level: "O1"

# data
image_size: [ 512, 512 ]
num_frames: 64
frame_stride: 2

num_parallel_workers: 16
max_rowsize: 256

# precision
amp_level: "O2"
vae_dtype: "bf16"
dtype: "bf16"
init_loss_scale: 65536

# training hyper-params
scheduler: "constant"
start_learning_rate: 2.e-5
end_learning_rate: 2.e-5
warmup_steps: 0   # TODO: ablate

batch_size: 1
clip_grad: True
max_grad_norm: 1.0
use_ema: False

optim: "adamw_re"
optim_eps: 1.e-8
weight_decay: 0.

epochs: 10000
ckpt_save_interval: 200

mask_ratios:
  mask_no: 0.75
  mask_quarter_random: 0.025
  mask_quarter_head: 0.025
  mask_quarter_tail: 0.025
  mask_quarter_head_tail: 0.05
  mask_image_random: 0.025
  mask_image_head: 0.025
  mask_image_tail: 0.025
  mask_image_head_tail: 0.05
