# model
model_version: v1.1
pretrained_model_path: "models/PixArt-XL-2-1024-MS.ckpt"
model_max_length: 200

enable_flash_attention: True
use_recompute: True

# data

num_frames: 16
max_image_size: 512
frame_stride: 3
pre_patchify: True

num_parallel_workers: 8
max_rowsize: 256

# precision
amp_level: "O2"
dtype: bf16
loss_scaler_type: static
init_loss_scale: 1

# training hyper-params
scheduler: "cosine_decay"
start_learning_rate: 1.e-4
end_learning_rate: 2.e-5
warmup_steps: 500   # TODO: ablate

batch_size: 1
clip_grad: True
max_grad_norm: 5.0
use_ema: False

optim: "adamw_re"
optim_eps: 1.e-8
weight_decay: 0.

epochs: 2000
ckpt_save_interval: 100

mask_ratios:
  identity: 0.75
  quarter_random: 0.025
  quarter_head: 0.025
  quarter_tail: 0.025
  quarter_head_tail: 0.05
  image_random: 0.025
  image_head: 0.025
  image_tail: 0.025
  image_head_tail: 0.05
