# model
model_version: v1.1
pretrained_model_path: "models/opensora_v1.1_stage3.ckpt"
model_max_length: 200
manual_pad: True

enable_flash_attention: True
use_recompute: True

# vae_micro_batch_size: 4
vae_dtype: bf16

# data
image_size: [ 512, 512 ]
num_frames: 16
frame_stride: 3

num_parallel_workers: 8
max_rowsize: 256

# precision
amp_level: "O2"
dtype: bf16
loss_scaler_type: static
init_loss_scale: 1

# training hyper-params
scheduler: "constant"
start_learning_rate: 2.e-5
end_learning_rate: 2.e-5
warmup_steps: 0

batch_size: 1
clip_grad: True
max_grad_norm: 1.0
use_ema: True

optim: "adamw_re"
optim_eps: 1.e-8
weight_decay: 0.

epochs: 2000
ckpt_save_interval: 100

mask_ratios:
  identity: 0.75
  quarter_random: 0.025
  quarter_head: 0.025
  quarter_tail: 0.025
  quarter_head_tail: 0.05
  image_random: 0.025
  image_head: 0.025
  image_tail: 0.025
  image_head_tail: 0.05

bucket_config:
  # Structure: "resolution": { num_frames: [ keep_prob, batch_size ] }
  # Setting [ keep_prob, batch_size ] to [ 0.0, 0 ] forces longer videos into smaller resolution buckets
  "144p": { 1: [ 1.0, 200 ], 16: [ 1.0, 8 ], 32: [ 1.0, 4 ], 64: [ 1.0, 2 ], 128: [ 1.0, 1 ] }
  "256": { 1: [ 0.8, 200 ], 16: [ 0.5, 8 ], 32: [ 0.5, 4 ], 64: [ 0.5, 2 ], 128: [ 0.8, 1 ] }
  "240p": { 1: [ 0.8, 200 ], 16: [ 0.5, 8 ], 32: [ 0.5, 4 ], 64: [ 0.5, 2 ], 128: [ 0.5, 1 ] }
  "360p": { 1: [ 0.5, 120 ], 16: [ 0.5, 9 ], 32: [ 0.5, 4 ], 64: [ 0.5, 2 ], 128: [ 0.5, 1 ] }
  "512": { 1: [ 0.5, 120 ], 16: [ 0.5, 4 ], 32: [ 0.5, 2 ], 64: [ 0.5, 1 ], 128: [ 0.0, 0 ] }
  "480p": { 1: [ 0.4, 80 ], 16: [ 0.6, 3 ], 32: [ 0.6, 1 ], 64: [ 0.0, 0 ] }
  "720p": { 1: [ 0.4, 40 ], 16: [ 0.6, 1 ], 96: [ 0.0, 0 ] }
  "1024": { 1: [ 0.3, 40 ] }
