TASK_TYPE: MULTI_TASK
ENABLE: true
DATASET: webvid10m
video_compositions: ['text', 'mask', 'depthmap', 'sketch', 'motion', 'image', 'local_image', 'single_sketch']
batch_sizes: {
    "1": 1,
    "4": 1,
    "8": 1,
    "16": 1,
}
vit_image_size: 224
network_name: UNetSD_temporal
resume: true
num_workers: 1
mvs_visual: False
chunk_size: 16
resume_checkpoint: "model_weights/non_ema_228000-7f157ec2.ckpt"
log_dir: 'outputs'
num_steps: 1
