TASK_TYPE: MULTI_TASK
ENABLE: true
DATASET: webvid10m
video_compositions: ['text', 'mask', 'depthmap', 'sketch', 'motion', 'image', 'local_image', 'single_sketch']
batch_sizes: {
    "1": 1,
    "4": 1,
    "8": 1,
    "16": 1,
}
vit_image_size: 224
network_name: UNetSD_temporal
resume: true
resume_step: 228000
num_workers: 1
mvs_visual: False
chunk_size: 1
resume_checkpoint: "non_ema_228000.pth"
log_dir: 'outputs'
num_steps: 1
