TASK_TYPE: SINGLE_TASK
ENABLE: true
DATASET: webvid10m
video_compositions: ['text', 'mask', 'depthmap', 'sketch', 'single_sketch', 'motion', 'image', 'local_image']
conditions_for_train: ['text', 'image', 'single_sketch']  # PyTorch + Ascend setting
vit_image_size: 224
network_name: UNetSD_temporal
resume: true
seed: 182
mvs_visual: False
chunk_size: 16
log_dir: 'outputs'
learning_rate: 0.00001 #0.00005 in paper, but we are finetuning.
epochs: 50

# accelerate or memory reduction
dataset_sink_mode: True
use_recompute: False  # use_recompute being True scarifices speed for more memory. Set it to True if OOM
