ToonYou:
  motion_module:
    - "models/motion_module/mm_sd_v15.ckpt"
    # - "outputs/train_infnan_bs4_toonyou_zoomin/ad_v2-2000.ckpt"

  dreambooth_path: "models/dreambooth_lora/toonyou_beta3.ckpt"
  lora_model_path: ""

  seed:           [1024, 434, 431, 42]
  steps:          30
  guidance_scale: 7.5

  prompt:
    - "best quality, masterpiece, 1girl, looking at viewer, blurry background, upper body, contemporary, dress"
    - "masterpiece, best quality, 1girl, solo, cherry blossoms, hanami, pink flower, white flower, spring season, wisteria, petals, flower, plum blossoms, outdoors, falling petals, white hair, black eyes,"
    - "best quality, masterpiece, 1boy, formal, abstract, looking at viewer, masculine, marble pattern"
    - "best quality, masterpiece, 1girl, cloudy sky, dandelion, contrapposto, alternate hairstyle,"

  n_prompt:
    - "worst quality, low quality, letterboxed"
    - "badhandv4,easynegative,ng_deepnegative_v1_75t,verybadimagenegative_v1.3, bad-artist, bad_prompt_version2-neg, teeth"
    - ""
    - ""
