python run_vae.py \
    --input-type folder \
    --real-video-dir datasets/MCL_JCV/ \
    --generated-video-dir "path/to/generated_videos" \
    --output-path datasets/MCL_JCV_generated/ \
    --height 336 \
    --width 336 \
    --num-frames 65 \
    --sample-rate 1 \
