text_config:
  vocab_size: 49408
  hidden_size: 512
  intermediate_size: 2048
  num_hidden_layers: 12
  num_attention_heads: 8
  max_position_embeddings: 77
  hidden_act: "quick_gelu"
  initializer_range: 0.02
  initializer_factor: 1.0

vision_config:
  hidden_size: 768
  intermediate_size: 3072
  num_hidden_layers: 12
  num_attention_heads: 12
  image_size: 224
  patch_size: 16
  hidden_act: "quick_gelu"
  initializer_range: 0.02
  initializer_factor: 1.0

dtype: float16  # type of tensors
projection_dim: 512  # feature dims
logit_scale_init_value: 2.6592
