model:
  base_learning_rate: 1.0e-05
  target: ad.models.diffusion.ddpm.LatentDiffusionWithEmbedding
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "caption"
    image_size: 64
    channels: 4
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    use_fp16: True

    unet_config:
      target: ad.modules.diffusionmodules.unet3d.UNet3DModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        use_fp16: True
        dropout: 0.1
        use_recompute: False # debug
        recompute_strategy: "down_blocks"
        enable_flash_attention: false
        # Additional args for mm v2
        use_inflated_groupnorm: true
        unet_use_cross_frame_attention: false
        unet_use_temporal_attention: false
        use_motion_module: true # debug
        motion_module_resolutions: [1, 2, 4, 8]
        motion_module_mid_block: true
        motion_module_decoder_only: false
        motion_module_type: Vanilla
        motion_module_kwargs:
          num_attention_heads: 8
          num_transformer_block: 1
          attention_block_types:
            - Temporal_Self
            - Temporal_Self
          temporal_position_encoding: true
          temporal_position_encoding_max_len: 32
          temporal_attention_dim_div: 1
          zero_initialize: true

    first_stage_config:
      target: ad.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        use_fp16: False
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []

    cond_stage_config:
      target: ad.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        use_fp16: True
        tokenizer_name: "BpeTokenizer"
        context_length: 77
        vocab_size: 49408
        output_dim: 768
        width: 768
        layers: 12
        heads: 12
        epsilon: 1e-5
        use_quick_gelu: True
