from_pretrained: hpcai-tech/Open-Sora-v2/hunyuan_vae.safetensors
in_channels: 3
out_channels: 3
layers_per_block: 2
latent_channels: 16
use_spatial_tiling: True
use_temporal_tiling: False
dtype: bf16
