model:
  name: sdxl-inference
  version: "sdxl"
  pretrained_ckpt: models/sd_xl_base_1.0_ms.ckpt
  target: gm.models.diffusion.DiffusionEngine
  params:
    scale_factor: 0.13025
    disable_first_stage_amp: True

    denoiser_config:
      target: gm.modules.diffusionmodules.denoiser.DiscreteDenoiser
      params:
        num_idx: 1000

        weighting_config:
          target: gm.modules.diffusionmodules.denoiser_weighting.EpsWeighting
        scaling_config:
          target: gm.modules.diffusionmodules.denoiser_scaling.EpsScaling
        discretization_config:
          target: gm.modules.diffusionmodules.discretizer.LegacyDDPMDiscretization

    network_config:
      target: gm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        adm_in_channels: 2816
        num_classes: sequential
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [4, 2]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 64
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: [1, 2, 10]  # note: the first is unused (due to attn_res starting at 2) 32, 16, 8 --> 64, 32, 16
        context_dim: 2048
        spatial_transformer_attn_type: vanilla  # vanilla, flash-attention
        legacy: False

    conditioner_config:
      target: gm.modules.GeneralConditioner
      params:
        emb_models:
          # crossattn cond
          - is_trainable: False
            input_key: txt
            target: gm.modules.embedders.modules.FrozenCLIPEmbedder
            params:
              layer: hidden
              layer_idx: 11
              version: openai/clip-vit-large-patch14
            tokenizer_name: CLIPTokenizer
              # pretrained: ''
          # crossattn and vector cond
          - is_trainable: False
            input_key: txt
            target: gm.modules.embedders.modules.FrozenOpenCLIPEmbedder2
            params:
              arch: ViT-bigG-14-Text
              freeze: True
              layer: penultimate
              always_return_pooled: True
              legacy: False
              require_pretrained: False
            tokenizer_name: OpenCLIPTokenizer
              # pretrained: ''  # laion2b_s32b_b79k.ckpt
          # vector cond
          - is_trainable: False
            input_key: original_size_as_tuple
            target: gm.modules.embedders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256  # multiplied by two
            tokenizer_name: IdentityTokenizer
          # vector cond
          - is_trainable: False
            input_key: crop_coords_top_left
            target: gm.modules.embedders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256  # multiplied by two
            tokenizer_name: IdentityTokenizer
          # vector cond
          - is_trainable: False
            input_key: target_size_as_tuple
            target: gm.modules.embedders.modules.ConcatTimestepEmbedderND
            params:
              outdim: 256  # multiplied by two
            tokenizer_name: IdentityTokenizer
    first_stage_config:
      target: gm.models.autoencoder.AutoencoderKLInferenceWrapper
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          attn_type: vanilla  # flash-attention
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: mindspore.nn.Identity
