# model
image_height: 512
image_width: 512
sample_size: 64
checkpoint: "models/PixArt-XL-2-512x512.ckpt"
vae_checkpoint: "models/sd-vae-ft-ema.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: True
dtype: "fp16"

# sampling
sampling_steps: 50
guidance_scale: 4.0
seed: 42
ddim_sampling: True
