# model
image_height: 256
image_width: 256
sample_size: 32
checkpoint: "models/PixArt-XL-2-256x256.ckpt"
vae_checkpoint: "models/sd-vae-ft-ema.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: True
dtype: "fp16"

# sampling
sampling_steps: 50
guidance_scale: 4.0
seed: 42
ddim_sampling: True
