# task
condition: "class"
output_path: outputs/class_cond_train

# system
use_parallel: True

# model setting
image_size: 256 # or 512
model_name: "DiT-XL/2"
dit_checkpoint: ""
vae_checkpoint: "models/sd-vae-ft-mse.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: False
dtype: "fp16"
use_recompute: False
patch_embedder: "conv"


# data setting
imagenet_format: True
data_path: imagenet_samples/images/
dataset_sink_mode: False
num_parallel_workers: 4

# training hyper-params
start_learning_rate: 1e-4
scheduler: "constant"
warmup_steps: 100
train_batch_size: 64
gradient_accumulation_steps: 1
weight_decay: 0.01
epochs: 1400

use_ema: True
clip_grad: True
ckpt_max_keep: 3
init_loss_scale: 65536

betas: [0.9, 0.999]
optim_eps: 1.e-6

# training process
log_interval: 1
ckpt_save_interval: 1
step_mode: False
