model_version: "kl"
generator:
  target: ae.models.autoencoder_kl.AutoencoderKL
  params:
    embed_dim: 4
    monitor: val/rec_loss
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

discriminator:
  target: ae.models.discriminator.NLayerDiscriminator

lossconfig:
  disc_start: 50001
  kl_weight: 1.0e-06
  disc_weight: 0.5
