python tests/test_data.py \
    --model OpenSoraT2V_v1_3-2B/122 \
    --text_encoder_name_1 google/mt5-xxl \
    --dataset t2v \
    --num_frames 93 \
    --data "scripts/train_data/merge_data_mixkit.txt" \
    --cache_dir "./" \
    --ae WFVAEModel_D8_4x8x8 \
    --ae_path "LanguageBind/Open-Sora-Plan-v1.3.0/vae" \
    --sample_rate 1 \
    --max_height 352 \
    --max_width 640 \
    --train_fps 16 \
    --force_resolution \
    --interpolation_scale_t 1.0 \
    --interpolation_scale_h 1.0 \
    --interpolation_scale_w 1.0 \
    --train_batch_size=8 \
    --dataloader_num_workers 20 \
    --output_dir="test_data/" \
    --model_max_length 512 \
