# The Minimum VRAM Requirement is around 12-16 GB. Longer video will not cost more.
pretrained_model_path: "stabilityai/stable-diffusion-2-depth"
output_dir: "./results/tuning-free-mix/car-turn"

train_data:
  video_path: "data/car-turn.mp4"
  prompt: "a jeep car is moving on the road"
  n_sample_frames: 10
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 2
  # delete the above lines uncomment the following lines for longer video.
  # sample_frame_rate: 1
validation_data:
  prompts:
   - - "a jeep car is running on the beach, sunny day"
     - "a jeep car is moving on the beach, night"
   - - "a jeep car is moving on the snow, sunny day"
     - "a jeep car is moving on the snow, night"
    # delete the above lines and uncomment the following lines for longer video.
    # - - "a jeep car is moving on the beach, sunny day"
    #   - "a jeep car is moving on the beach, sunny day"
    #   - "a jeep car is moving on the beach, night"
    #   - "a jeep car is moving on the beach, night"
    # - - "a jeep car is moving on the snow, sunny day"
    #   - "a jeep car is moving on the snow, sunny day"
    #   - "a jeep car is moving on the snow, night"
    #   - "a jeep car is moving on the snow, night"
    # - - "a jeep car is moving on the beach, sunny day"
    #   - "a jeep car is moving on the beach, night"
    #   - "a jeep car is moving on the beach, sunny day"
    #   - "a jeep car is moving on the beach, night"
    # - - "a jeep car is moving on the snow, sunny day"
    #   - "a jeep car is moving on the snow, night"
    #   - "a jeep car is moving on the snow, sunny day"
    #   - "a jeep car is moving on the snow, night"
  video_length: 5
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50
  stride: 5
  use_l2: False
run_isolated: True
train_batch_size: 1
seed: 33
amp_level: "O0"
