target: glv.schedulers.scheduling_ddim.DDIMScheduler
params:
  beta_end: 0.012
  beta_schedule: "scaled_linear"
  beta_start: 0.00085
  clip_sample: False
  num_train_timesteps: 1000
  prediction_type: "epsilon"
  set_alpha_to_one: False
  steps_offset: 1
  trained_betas: null
