# system
mode: 0
use_parallel: False

# dataset
data_path: dataset/fill50k
random_crop: False
image_size: 512
train_batch_size: 4
control_type: canny

# model
version: "1.5"
model_config: "configs/v1-train-controlnet.yaml"
output_path: "/path/to/save/output_data"
ckpt_save_interval: 1
epochs: 4

# lr scheduler
scheduler: constant
start_learning_rate: 1e-5

# optimizer
optim: "adamw"
betas: [0.9, 0.98]
weight_decay: 0.01
