# system
mode: 0
use_parallel: False
num_workers: 1

# dataset
data_path: "/path/to/data"
train_batch_size: 1
image_size: 768
image_filter_size: 256

# model
model_config: "configs/v2-vpred-train.yaml"
pretrained_model_path: "/path/to/pretrained_model"
output_path: "/path/to/save/output_data"
ckpt_save_interval: 1
epochs: 20
use_ema: True
clip_grad: False

# lr scheduler
scheduler: "cosine_decay"
start_learning_rate: 1e-5
end_learning_rate: 1e-7
warmup_steps: 1000
decay_steps: 0

# optimizer
optim: "adamw"
betas: [0.9, 0.98]
weight_decay: 0.01
