# system
mode: 0
use_parallel: False

# dataset
train_data_dir: "datasets/cat_toy"
placeholder_token: "<cat-toy>"
initializer_token: "toy"
learnable_property: "object"
num_vectors: 3
random_crop: True
train_batch_size: 1
image_size: 512

# model
version: "2.0"
model_config: "configs/v2-train-textual-inversion.yaml"
output_path: "/path/to/save/output_data"
ckpt_save_interval: 500
max_steps: 6000
use_ema: False
clip_grad: True
gradient_accumulation_steps: 4

# lr
start_learning_rate: 5e-5
scale_lr: True
scheduler: "multi_step_decay"
milestones: [200, 400, 800, 1600, 3200]
decay_rate: 0.9


# optimizer
optim: "adamw"
betas: [0.9, 0.98]
weight_decay: 1e-2
