# system
mode: 0
use_parallel: False
num_workers: 1
seed: 1337

# dataset
data_path: "/path/to/data"
train_batch_size: 4
image_size: 512
image_filter_size: 200

# model
model_config: "configs/v1-train.yaml"
pretrained_model_path: "/path/to/pretrained_model"
output_path: "/path/to/save/output_data"
ckpt_save_interval: 5
epochs: 72
use_ema: False #True
clip_grad: True

# lr scheduler
scheduler: "cosine_decay"
start_learning_rate: 1.e-4
end_learning_rate: 0
warmup_steps: 5
decay_steps: 0

# optimizer
optim: "adamw"
betas: [0.9, 0.98]
weight_decay: 0.01

# lora
use_lora: True
lora_ft_text_encoder: False
lora_rank: 128
lora_fp16: True
