# system
mode: 0
use_parallel: False

# dataset
video_path: "videos/man-skiing.mp4"
prompt: "a man is skiing"
num_frames: 12  # use 24 (910B) or 12 (910A)
sample_start_idx: 0
sample_interval: 2
image_size: 512
train_batch_size: 1

# model
version: "2.0"
model_config: "configs/v2-train-tuneavideo.yaml"
output_path: "./outputs/man-skiing"
ckpt_save_interval: 250
max_train_steps: 500
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

# lr scheduler
start_learning_rate: 3e-5
scheduler: "constant"


# optimizer
optim: "adamw"
betas: [0.9, 0.98]
weight_decay: 0.01
