python sample_video.py \
    --video-size 240 320 \
    --video-length 17 \
    --infer-steps 2 \
    --prompt "A cat walks on the grass, realistic style." \
    --flow-reverse \
    --seed-type 'fixed' \
    --seed 42 \
    --save-path ./results \
    --precision 'bf16' \
    --attn-mode 'flash' \
    --model  "HYVideo-T/2-depth1" \
    --dit-weight 'ckpts/transformer_depth1.pt' \
    --output-type 'latent' \
    --text-embed-path 'pt_io/text_embed_with_neg-A-cat-wa.npz' \
