# model
image_height: 2048
image_width: 2048
sample_size: 256
checkpoint: "models/PixArt-Sigma-XL-2-2K-MS.ckpt"
vae_root: "models/vae"
text_encoder_root: "models/text_encoder"
tokenizer_root: "models/tokenizer"
sd_scale_factor: 0.13025
enable_flash_attention: True
dtype: "fp16"

# sampling
sampling_method: "dpm"
sampling_steps: 20
guidance_scale: 4.5
seed: 42

prompt:
  - "A small cactus with a happy face in the Sahara desert."
